### ISSUE TITLE
https://transcri.streamlit.app/

### ISSUE THREAD

**Issue by ruilacerda** [felipesanma/y2t#1]
Oh no.

Error running app. If this keeps happening, please [contact support](https://github.com/felipesanma/y2t/issues/new).

**Comment by felipesanma** [comment]
Solve it. Reboot App.

**Comment by felipesanma** [comment]
It run out of resources, so after reboot app and disconnect all sessions, works again (streamlit free resources are limited)

**Comment by felipesanma** [comment]
It run out of resources, so after reboot app and disconnect all sessions, works again (streamlit free resources are limited)
